name: Build and Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Run build
      run: echo 'Mock build successful!'
    - name: Display success message
      run: echo 'Build and test successful!'